// Shared renderer used by Stage 05 (live SSE stream) and the
// /api/sessions/[id]?download=md endpoint. Extracted so both call sites
// produce identical output for a given workflow.

import type { GenerateOutput, SimulateOutput } from './workflow-types';

export function renderAgentSwarmPromptFromSession(
  generate: GenerateOutput,
  simulate: SimulateOutput
): string {
  const lines: string[] = [];
  const stepsWithPrompt = generate.steps.filter((s) => s.prompt);
  const llmSteps = generate.steps.filter((s) => s.model !== 'deterministic').length;
  const detSteps = generate.steps.length - llmSteps;
  const humanGates = generate.steps.filter((s) => s.actor === 'human').length;

  lines.push(`# Agent Swarm Prompt: ${generate.workflow_name}`, '');
  lines.push(`*Generated by BoVerse · ${new Date().toISOString()}*`, '');
  lines.push('## Mission', '');
  lines.push(generate.workflow_description, '');
  lines.push(
    `Execute this workflow against a batch of input rows shaped to the **Input contract** below. ${generate.steps.length} steps total: ${llmSteps} LLM-driven, ${detSteps} deterministic, ${humanGates} human gates.`,
    ''
  );
  lines.push(`**Success criteria.** For each input row, the swarm must:`, '');
  lines.push('1. Produce a complete output that conforms to the **Output contract** (last section).');
  lines.push('2. Surface any human-gate decisions for review rather than silently approving them.');
  lines.push('3. When an **Edge-case dossier** condition fires, log which rule triggered and how the workflow handled it.');
  lines.push('4. Maintain a per-step trace so the run is auditable end-to-end.', '');

  lines.push('## Input contract', '');
  lines.push('Each input row is a JSON object with the following fields:', '');
  lines.push('| Field | Type | Required | Description |');
  lines.push('|---|---|---|---|');
  for (const f of simulate.schema) {
    const type = f.type === 'enum' ? `enum(${(f.enum_values ?? []).join(' \\| ')})` : f.type;
    lines.push(`| \`${f.name}\` | ${type} | ${f.required ? 'yes' : 'no'} | ${f.description} |`);
  }
  lines.push('');
  lines.push('### Example inputs', '');
  const sampleHappy = simulate.rows.find((r) => r.kind === 'happy');
  const sampleEdge = simulate.rows.find((r) => r.kind === 'edge');
  if (sampleHappy) {
    lines.push('**Happy-path example:**');
    lines.push('```json');
    lines.push(JSON.stringify(sampleHappy.data, null, 2));
    lines.push('```', '');
  }
  if (sampleEdge) {
    lines.push(`**Edge-case example** — ${sampleEdge.edge_case_description ?? 'unspecified'}:`);
    lines.push('```json');
    lines.push(JSON.stringify(sampleEdge.data, null, 2));
    lines.push('```', '');
  }

  lines.push('## Edge-case dossier', '');
  const edges = simulate.rows.filter((r) => r.kind === 'edge');
  if (edges.length === 0) {
    lines.push('No edge cases enumerated. Treat unusual inputs conservatively and surface for human review.', '');
  } else {
    lines.push(
      'These are the failure modes the synthetic dataset deliberately tests. The swarm should detect each one and route appropriately:',
      ''
    );
    edges.forEach((row, i) => {
      lines.push(`${i + 1}. **${row.edge_case_description ?? 'Unspecified edge case'}**`);
      lines.push('   ```json');
      lines.push('   ' + JSON.stringify(row.data, null, 2).split('\n').join('\n   '));
      lines.push('   ```');
    });
    lines.push('');
  }

  lines.push('## Agent roster', '');
  lines.push('One agent per step. Assign these personas to your swarm:', '');
  lines.push('| Step ID | Agent name | Role | Actor | Model |');
  lines.push('|---|---|---|---|---|');
  for (const step of generate.steps) {
    const persona = personaForStep(step);
    lines.push(`| \`${step.id}\` | **${persona}** | ${step.name} | ${step.actor} | \`${step.model}\` |`);
  }
  lines.push('');

  lines.push('## Execution graph', '');
  lines.push(
    "Steps run in the order listed. Each step's **Inputs** come from earlier steps' outputs or the original row.",
    ''
  );
  for (const step of generate.steps) {
    lines.push(`### ${step.id} — ${step.name}`, '');
    lines.push(`- **Primitive**: \`${step.primitive}\``);
    lines.push(`- **Actor**: ${step.actor}${step.actor === 'human' ? ' *(STOP here, route to human reviewer)*' : ''}`);
    lines.push(`- **Model**: \`${step.model}\``);
    lines.push(`- **Inputs**: ${step.inputs.length ? step.inputs.map((s) => `\`${s}\``).join(', ') : '*(none — origin step)*'}`);
    lines.push(`- **Outputs**: ${step.outputs.length ? step.outputs.map((s) => `\`${s}\``).join(', ') : '*(side effect only)*'}`);
    if (step.rag_assets?.length)
      lines.push(`- **Knowledge to retrieve**: ${step.rag_assets.map((s) => `\`${s}\``).join(', ')}`);
    lines.push(`- **Why this step exists**: ${step.rationale}`);
    if (step.prompt) {
      lines.push('', '#### Prompt template', '');
      lines.push('```text');
      lines.push(step.prompt);
      lines.push('```');
    } else if (step.model === 'deterministic') {
      lines.push('', '*(Deterministic step — no LLM call. Implement as a pure function over the listed inputs.)*');
    }
    lines.push('');
  }

  lines.push('## Knowledge base (RAG)', '');
  if (!generate.rag_library.length) {
    lines.push(
      'No knowledge assets declared. Steps marked with `rag_assets` references should be skipped or treated as deterministic.',
      ''
    );
  } else {
    lines.push(
      'When a step lists **Knowledge to retrieve**, fetch the matching asset(s) below and include the content in the LLM call as context. These are stored in Supabase pgvector keyed by `asset_name` — query by exact name or cosine similarity on the embedding.',
      ''
    );
    for (const asset of generate.rag_library) {
      lines.push(`### \`${asset.asset_name}\` *(${asset.asset_type})*`);
      lines.push(asset.description, '');
    }
  }

  lines.push('## Output contract', '');
  lines.push('For each input row, emit a JSON object with this shape:', '');
  lines.push('```typescript');
  lines.push('{');
  lines.push('  row_id: string;                          // copy from input');
  lines.push('  status: "success" | "human_gated" | "failure";');
  lines.push('  step_results: Array<{');
  lines.push('    step_id: string;');
  lines.push('    step_name: string;');
  lines.push('    status: "success" | "failure" | "gated_for_human" | "skipped";');
  lines.push('    duration_ms: number;');
  lines.push("    output: Record<string, unknown>;       // per the step's declared outputs");
  lines.push('    trace_message: string;                 // 1-2 sentence audit note');
  lines.push('    retrieved_assets?: Array<{ asset_name: string; similarity: number }>;');
  lines.push('  }>;');
  lines.push('  edge_case_detected?: string;             // if a dossier rule fired');
  lines.push('  human_review_needed?: string;            // why, if status === "human_gated"');
  lines.push('}');
  lines.push('```', '');
  lines.push('---', '');
  lines.push(
    `Total steps: ${generate.steps.length}  ·  Schema fields: ${simulate.schema.length}  ·  Synthetic rows tested: ${simulate.rows.length}  ·  LLM prompts: ${stepsWithPrompt.length}  ·  RAG assets: ${generate.rag_library.length}`
  );

  return lines.join('\n');
}

function personaForStep(step: GenerateOutput['steps'][number]): string {
  const words = step.name
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 3)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase());
  return words.join(' ') || step.id;
}
