// In-process .docx renderer using the Node `docx` library.
// Produces the same OOXML format as python-docx (both follow the OOXML
// spec strictly). Runs in the Next.js process — no separate Python service,
// no Vercel multi-project complexity.
//
// Layout mirrors the python-docx version: title block, execution summary
// table, input schema table, per-step sections with primitive/actor/model
// metadata and prompt templates in monospace, RAG library bullets.

import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  TextRun,
  HeadingLevel,
  AlignmentType,
  WidthType,
  BorderStyle,
  ShadingType,
} from 'docx';
import type {
  GenerateOutput,
  SimulateOutput,
  DeliverOutput,
} from './workflow-types';

// ─── Small helpers ───────────────────────────────────────────────────────

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel]) {
  return new Paragraph({ heading: level, children: [new TextRun({ text })] });
}

function text(content: string, opts: { italics?: boolean; bold?: boolean; size?: number; color?: string } = {}) {
  return new Paragraph({
    children: [new TextRun({ text: content, ...opts })],
  });
}

function mono(content: string, size = 18) {
  return new Paragraph({
    children: [new TextRun({ text: content, font: 'Consolas', size })],
    shading: { type: ShadingType.CLEAR, color: 'auto', fill: 'F4F4F5' },
  });
}

const thinBorder = { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC' };

function kvCell(content: string, opts: { bold?: boolean } = {}) {
  return new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: content, bold: opts.bold })] })],
    borders: { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder },
  });
}

function kvTable(rows: Array<[string, string]>): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map(
      ([k, v]) =>
        new TableRow({
          children: [kvCell(k, { bold: true }), kvCell(v)],
        })
    ),
  });
}

// ─── Main renderer ───────────────────────────────────────────────────────

export async function renderWorkflowDocx(
  workflow: GenerateOutput,
  simulate: SimulateOutput,
  executionSummary: DeliverOutput['execution_summary'] | null,
  generatedOn: string
): Promise<Buffer> {
  const children: Array<Paragraph | Table> = [];

  // ── Title ───────────────────────────────────────────────────────────
  children.push(heading(workflow.workflow_name, HeadingLevel.TITLE));
  children.push(
    new Paragraph({
      alignment: AlignmentType.LEFT,
      children: [
        new TextRun({
          text: `Generated by BoVerse · ${generatedOn}`,
          italics: true,
          size: 20,
          color: '606060',
        }),
      ],
    })
  );
  children.push(text(''));
  children.push(text(workflow.workflow_description));
  children.push(text(''));

  // ── Execution summary ───────────────────────────────────────────────
  if (executionSummary) {
    const s = executionSummary;
    children.push(heading('Execution summary', HeadingLevel.HEADING_1));
    children.push(
      kvTable([
        ['Total synthetic rows', String(s.total_rows)],
        ['Happy-path rows passed', `${s.happy_rows_passed} / ${s.total_rows - 3}`],
        ['Edge cases triggered correctly', `${s.edge_rows_caught} / 3`],
        ['Total LLM calls', String(s.total_llm_calls)],
        ['Total execution time', `${(s.total_duration_ms / 1000).toFixed(1)} s`],
      ])
    );
    children.push(text(''));
  }

  // ── Input schema ────────────────────────────────────────────────────
  children.push(heading('Input schema', HeadingLevel.HEADING_1));
  const schemaHeaderCells = ['Field', 'Type', 'Required', 'Description'].map(
    (h) =>
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })],
        borders: { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder },
      })
  );
  const schemaRows: TableRow[] = [new TableRow({ children: schemaHeaderCells })];
  for (const f of simulate.schema) {
    const typeStr = f.type === 'enum' ? `enum(${(f.enum_values ?? []).join(', ')})` : f.type;
    schemaRows.push(
      new TableRow({
        children: [
          kvCell(f.name),
          kvCell(typeStr),
          kvCell(f.required ? 'yes' : 'no'),
          kvCell(f.description),
        ],
      })
    );
  }
  children.push(
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: schemaRows })
  );
  children.push(text(''));

  // ── Workflow steps ──────────────────────────────────────────────────
  children.push(heading('Workflow steps', HeadingLevel.HEADING_1));
  for (const step of workflow.steps) {
    children.push(heading(`${step.id} — ${step.name}`, HeadingLevel.HEADING_2));

    const metaRows: Array<[string, string]> = [
      ['Primitive', step.primitive],
      ['Actor', step.actor],
      ['Model', step.model],
    ];
    if (step.inputs.length) metaRows.push(['Inputs', step.inputs.join(', ')]);
    if (step.outputs.length) metaRows.push(['Outputs', step.outputs.join(', ')]);
    if (step.rag_assets?.length) metaRows.push(['RAG assets', step.rag_assets.join(', ')]);
    children.push(kvTable(metaRows));

    children.push(text(''));
    children.push(text(step.rationale, { italics: true }));

    if (step.prompt) {
      children.push(text(''));
      children.push(text('Prompt template:', { bold: true }));
      // Render prompt as monospace block.
      for (const line of step.prompt.split('\n')) children.push(mono(line || ' '));
    }

    children.push(text(''));
  }

  // ── RAG library ─────────────────────────────────────────────────────
  children.push(heading('RAG library', HeadingLevel.HEADING_1));
  for (const asset of workflow.rag_library) {
    children.push(
      new Paragraph({
        bullet: { level: 0 },
        children: [
          new TextRun({ text: `${asset.asset_name} `, bold: true }),
          new TextRun({ text: `(${asset.asset_type}) — ${asset.description}` }),
        ],
      })
    );
  }

  // ── Footer ─────────────────────────────────────────────────────────
  children.push(text(''));
  children.push(
    text(
      'This document was generated automatically. Workflow primitives ' +
        '(ingest, transform, validate, action, feedback) and execution ' +
        'model are part of the BoVerse Workflow Factory v1 specification.',
      { italics: true, size: 16, color: '808080' }
    )
  );

  const doc = new Document({
    creator: 'BoVerse',
    title: workflow.workflow_name,
    description: workflow.workflow_description,
    sections: [{ children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
