"""
BoVerse workflow → .docx renderer.

Tiny FastAPI service that takes a generated workflow + simulate output +
optional execution summary and emits a production-grade Word document
using python-docx. Designed to live next to the Next.js app on Fly.io.

The Next.js Stage 05 route POSTs to /render and gets back a .docx binary.

Run locally:
  pip install -r requirements.txt
  uvicorn main:app --host 0.0.0.0 --port 8080 --reload
"""

from __future__ import annotations

import io
from typing import Any

from fastapi import FastAPI
from fastapi.responses import Response
from pydantic import BaseModel
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

app = FastAPI(title="BoVerse docx renderer", version="0.1.0")


# ─── Request schemas ─────────────────────────────────────────────────────────


class SchemaField(BaseModel):
    name: str
    type: str
    description: str
    required: bool
    enum_values: list[str] | None = None


class WorkflowStep(BaseModel):
    id: str
    name: str
    primitive: str
    actor: str
    model: str
    prompt: str | None = None
    inputs: list[str]
    outputs: list[str]
    rag_assets: list[str] | None = None
    rationale: str


class RagAsset(BaseModel):
    asset_name: str
    asset_type: str
    description: str


class GenerateOutput(BaseModel):
    workflow_name: str
    workflow_description: str
    steps: list[WorkflowStep]
    rag_library: list[RagAsset]


class SimulateOutput(BaseModel):
    schema: list[SchemaField]
    rows: list[dict[str, Any]]


class ExecutionSummary(BaseModel):
    total_rows: int
    happy_rows_passed: int
    edge_rows_caught: int
    total_llm_calls: int
    total_duration_ms: int


class RenderRequest(BaseModel):
    workflow: GenerateOutput
    simulate: SimulateOutput
    execution_summary: ExecutionSummary | None = None
    generated_on: str  # ISO date


# ─── Rendering ──────────────────────────────────────────────────────────────


def _set_run_mono(run, size: int = 9) -> None:
    """Format a run as monospace (Consolas) at the given point size."""
    run.font.name = "Consolas"
    run.font.size = Pt(size)


def _add_heading(doc: Document, text: str, level: int = 1) -> None:
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0x00, 0x00, 0x00)


def _add_kv_table(doc: Document, rows: list[tuple[str, str]]) -> None:
    """Two-column key/value table — used for metadata blocks."""
    table = doc.add_table(rows=len(rows), cols=2)
    table.style = "Light Grid Accent 1"
    for i, (k, v) in enumerate(rows):
        table.cell(i, 0).text = k
        table.cell(i, 1).text = v


def render_workflow_doc(req: RenderRequest) -> bytes:
    """Render the workflow spec to a .docx and return raw bytes."""
    doc = Document()

    # Margins
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # Title page
    title = doc.add_heading(req.workflow.workflow_name, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT

    subtitle = doc.add_paragraph()
    subtitle_run = subtitle.add_run("Generated by BoVerse · " + req.generated_on)
    subtitle_run.italic = True
    subtitle_run.font.size = Pt(10)
    subtitle_run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    doc.add_paragraph()
    desc = doc.add_paragraph(req.workflow.workflow_description)
    desc.paragraph_format.space_after = Pt(18)

    # Execution summary (if present)
    if req.execution_summary:
        _add_heading(doc, "Execution summary", level=1)
        s = req.execution_summary
        _add_kv_table(
            doc,
            [
                ("Total synthetic rows", str(s.total_rows)),
                ("Happy-path rows passed", f"{s.happy_rows_passed} / {s.total_rows - 3}"),
                ("Edge cases triggered correctly", f"{s.edge_rows_caught} / 3"),
                ("Total LLM calls", str(s.total_llm_calls)),
                ("Total execution time", f"{s.total_duration_ms / 1000:.1f} s"),
            ],
        )
        doc.add_paragraph()

    # Input schema
    _add_heading(doc, "Input schema", level=1)
    schema_table = doc.add_table(rows=1 + len(req.simulate.schema), cols=4)
    schema_table.style = "Light Grid Accent 1"
    hdr = schema_table.rows[0].cells
    for i, name in enumerate(["Field", "Type", "Required", "Description"]):
        hdr[i].text = name
    for i, f in enumerate(req.simulate.schema):
        row = schema_table.rows[i + 1].cells
        type_str = f"enum({', '.join(f.enum_values or [])})" if f.type == "enum" else f.type
        row[0].text = f.name
        row[1].text = type_str
        row[2].text = "yes" if f.required else "no"
        row[3].text = f.description
    doc.add_paragraph()

    # Workflow steps
    _add_heading(doc, "Workflow steps", level=1)
    for step in req.workflow.steps:
        _add_heading(doc, f"{step.id} — {step.name}", level=2)

        meta_rows: list[tuple[str, str]] = [
            ("Primitive", step.primitive),
            ("Actor", step.actor),
            ("Model", step.model),
        ]
        if step.inputs:
            meta_rows.append(("Inputs", ", ".join(step.inputs)))
        if step.outputs:
            meta_rows.append(("Outputs", ", ".join(step.outputs)))
        if step.rag_assets:
            meta_rows.append(("RAG assets", ", ".join(step.rag_assets)))
        _add_kv_table(doc, meta_rows)

        rationale_para = doc.add_paragraph()
        rationale_run = rationale_para.add_run(step.rationale)
        rationale_run.italic = True

        if step.prompt:
            prompt_heading = doc.add_paragraph()
            prompt_heading.add_run("Prompt template:").bold = True
            prompt_para = doc.add_paragraph()
            prompt_run = prompt_para.add_run(step.prompt)
            _set_run_mono(prompt_run, 9)

        doc.add_paragraph()

    # RAG library
    _add_heading(doc, "RAG library", level=1)
    for asset in req.workflow.rag_library:
        p = doc.add_paragraph(style="List Bullet")
        bold = p.add_run(f"{asset.asset_name} ")
        bold.bold = True
        p.add_run(f"({asset.asset_type}) — {asset.description}")

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        "This document was generated automatically. Workflow primitives "
        "(ingest, transform, validate, action, feedback) and execution "
        "model are part of the BoVerse Workflow Factory v1 specification."
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    footer_run.italic = True

    # Serialize
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ─── Routes ─────────────────────────────────────────────────────────────────


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "boverse-docx", "version": "0.1.0"}


@app.post("/render")
def render(req: RenderRequest) -> Response:
    data = render_workflow_doc(req)
    filename = (
        "".join(c if c.isalnum() else "-" for c in req.workflow.workflow_name.lower())
        .strip("-")[:80]
        + ".docx"
    )
    return Response(
        content=data,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
